# Generated by Django 3.0.5 on 2020-04-30 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0005_auto_20200430_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cpf',
            name='numero',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
