# Generated by Django 3.0.5 on 2020-05-02 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0009_empregado_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empregado',
            name='foto',
            field=models.ImageField(upload_to='cliente_fotos'),
        ),
    ]
